"""L402 Lightning-gated authentication (TB3 trust boundary).

Implements L402Client (agent-side 4-step payment flow) and L402Verifier
(service-side challenge creation and 5-check verification) with identity-bound
macaroons containing BIP340 pubkeys.

Flow: GET resource -> 402 + WWW-Authenticate header -> pay invoice -> retry with token.
Runs on LND regtest (benchmarks) or testnet (network-realistic validation).
No mainnet, no production channel management.

Algorithm reference: paper Section 4 (L402 unified flow; 4-step protocol,
macaroon identifier structure, 5-check verification, caveat attenuation).
"""

from __future__ import annotations

import base64
import logging
import os
import re
import struct
import time

import httpx
import pymacaroons  # type: ignore[import]

from nostr_agent.crypto import sha256, sign_schnorr, verify_schnorr
from nostr_agent.types import (
    L402AmountExceededError,
    L402Challenge,
    L402ParseError,
    L402PaymentError,
    L402VerificationResult,
    LndConnectionError,
    PaymentResult,
)

# Optional LND gRPC stubs -- generated by code/infra/compile_lnd_protos.sh.
# Import fails gracefully if stubs are not compiled yet.
try:
    from nostr_agent.lnd_grpc import lightning_pb2_grpc  # type: ignore[import]
    from nostr_agent.lnd_grpc import router_pb2_grpc  # type: ignore[import]
    from nostr_agent.lnd_grpc import lightning_pb2  # type: ignore[import]
    from nostr_agent.lnd_grpc import router_pb2  # type: ignore[import]

    _HAS_LND_STUBS = True
except ImportError:
    _HAS_LND_STUBS = False

from nostr_agent.lnd_grpc.credentials import (
    create_lnd_channel,
    load_macaroon,
    load_tls_cert,
)

logger = logging.getLogger(__name__)

# WWW-Authenticate header regex for L402 challenges.
_L402_RE = re.compile(
    r'L402\s+macaroon="(?P<macaroon>[^"]+)",\s*invoice="(?P<invoice>[^"]+)"',
    re.IGNORECASE,
)

# Identifier version byte.
_IDENTIFIER_VERSION = 0x01

# Timestamp freshness window (seconds).
_TIMESTAMP_WINDOW = 300

# Default max fee for Lightning payments (satoshis).
_DEFAULT_MAX_FEE_SAT = 10


# ============================================================================
# L402Client -- agent-side L402 payment flow (Steps 1-4)
# ============================================================================


class L402Client:
    """Agent-side L402 payment flow (Steps 1-4).

    Executes the full L402 protocol: identity presentation, challenge parsing,
    Lightning payment, and authenticated request with BIP340-signed credential.
    """

    def __init__(
        self,
        identity,  # AgentIdentity from identity.py
        lnd_host: str = "localhost",
        lnd_port: int = 10009,
        lnd_macaroon_path: str | None = None,
        lnd_tls_cert_path: str | None = None,
        max_auto_pay_sat: int = 1000,
    ) -> None:
        """Initialize L402 client with agent identity and LND connection.

        Args:
            identity: Active Kind 38100 AgentIdentity instance.
            lnd_host: LND gRPC host.
            lnd_port: LND gRPC port.
            lnd_macaroon_path: Path to LND admin macaroon.
            lnd_tls_cert_path: Path to LND TLS certificate.
            max_auto_pay_sat: Maximum auto-pay amount in satoshis.
        """
        self._identity = identity
        self._lnd_host = lnd_host
        self._lnd_port = lnd_port
        self._lnd_macaroon_path = lnd_macaroon_path
        self._lnd_tls_cert_path = lnd_tls_cert_path
        self._max_auto_pay_sat = max_auto_pay_sat

        # gRPC state (set on connect).
        self._channel = None  # grpc.aio.Channel
        self._lightning_stub = None
        self._router_stub = None

        # Required for LND TLS with self-signed certs.
        os.environ.setdefault("GRPC_SSL_CIPHER_SUITES", "HIGH+ECDSA")

    async def connect_lnd(self) -> bool:
        """Establish gRPC connection to LND node.

        Returns:
            True if connection succeeded.

        Raises:
            LndConnectionError: If connection fails or stubs are missing.
        """
        if not _HAS_LND_STUBS:
            raise LndConnectionError(
                "LND gRPC stubs not found. Run: bash code/infra/compile_lnd_protos.sh"
            )

        if self._lnd_macaroon_path is None or self._lnd_tls_cert_path is None:
            raise LndConnectionError(
                "lnd_macaroon_path and lnd_tls_cert_path are required for connect_lnd()"
            )

        try:
            macaroon_hex = load_macaroon(self._lnd_macaroon_path)
            tls_cert_bytes = load_tls_cert(self._lnd_tls_cert_path)

            self._channel = create_lnd_channel(
                self._lnd_host,
                self._lnd_port,
                macaroon_hex,
                tls_cert_bytes,
            )

            self._lightning_stub = lightning_pb2_grpc.LightningStub(self._channel)
            self._router_stub = router_pb2_grpc.RouterStub(self._channel)

            # Verify connection with GetInfo.
            info = await self._lightning_stub.GetInfo(lightning_pb2.GetInfoRequest())
            logger.info(
                "Connected to LND node: alias=%s, pubkey=%s",
                info.alias,
                info.identity_pubkey,
            )
            return True

        except Exception as e:
            self._channel = None
            self._lightning_stub = None
            self._router_stub = None
            raise LndConnectionError(f"Failed to connect to LND: {e}") from e

    async def request_with_l402(
        self,
        method: str,
        url: str,
        body: bytes | None = None,
        max_amount_sat: int | None = None,
    ) -> httpx.Response:
        """Execute full L402 flow (Steps 1-4).

        Step 1: Send request with X-Nostr-Pubkey header.
        Step 2: Parse 402 response (macaroon + invoice).
        Step 3: Pay Lightning invoice via LND SendPaymentV2.
        Step 4: Re-send with Authorization header (L402 macaroon:preimage)
                and X-Nostr-Sig (BIP340 signature over canonical request).

        Args:
            method: HTTP method (GET, POST, etc.).
            url: Full request URL.
            body: Request body bytes (optional, for POST).
            max_amount_sat: Override max auto-pay. Defaults to constructor value.

        Returns:
            Final HTTP response from Step 4.

        Raises:
            L402PaymentError: If Lightning payment fails.
            L402ParseError: If 402 response header is malformed.
            L402AmountExceededError: If invoice amount exceeds max_amount_sat.
        """
        effective_max = max_amount_sat if max_amount_sat is not None else self._max_auto_pay_sat
        pubkey_hex = self._identity.pubkey_hex

        async with httpx.AsyncClient(verify=False, timeout=30.0) as client:
            # --- Step 1: Identity presentation + resource request ---
            identity_headers = {"X-Nostr-Pubkey": pubkey_hex}
            step1_resp = await client.request(
                method, url, headers=identity_headers, content=body,
            )

            # No L402 required -- return directly.
            if step1_resp.status_code != 402:
                return step1_resp

            # --- Step 2: Parse 402 challenge ---
            challenge = self._parse_l402_challenge(step1_resp)

            # Validate invoice before paying.
            self._validate_invoice(
                challenge.bolt11_invoice, challenge.macaroon_bytes, effective_max,
            )

            # --- Step 3: Pay Lightning invoice ---
            payment = await self._pay_invoice(challenge.bolt11_invoice, effective_max)

            # --- Step 4: Authenticated request ---
            macaroon_b64 = base64.urlsafe_b64encode(challenge.macaroon_bytes).decode()
            preimage_hex = payment.preimage.hex()
            timestamp = int(time.time())
            sig_hex = self._sign_request(method, url, timestamp, body)

            auth_headers = {
                "Authorization": f"L402 {macaroon_b64}:{preimage_hex}",
                "X-Nostr-Pubkey": pubkey_hex,
                "X-Nostr-Sig": sig_hex,
                "X-Nostr-Timestamp": str(timestamp),
            }

            step4_resp = await client.request(
                method, url, headers=auth_headers, content=body,
            )
            return step4_resp

    def _parse_l402_challenge(self, response: httpx.Response) -> L402Challenge:
        """Parse WWW-Authenticate header from 402 response.

        Extracts base64-encoded macaroon and BOLT11 invoice. Decodes the
        macaroon identifier to extract payment_hash and agent_pubkey.

        Args:
            response: HTTP 402 response.

        Returns:
            L402Challenge with macaroon_bytes, bolt11_invoice, payment_hash, amount_sat.

        Raises:
            L402ParseError: If header is malformed or identifier invalid.
        """
        www_auth = response.headers.get("WWW-Authenticate", "")
        m = _L402_RE.search(www_auth)
        if not m:
            raise L402ParseError(
                f"Could not parse L402 challenge from header: {www_auth!r}"
            )

        macaroon_b64 = m.group("macaroon")
        bolt11 = m.group("invoice")

        # Decode macaroon bytes.
        try:
            macaroon_bytes = base64.urlsafe_b64decode(macaroon_b64)
        except Exception as e:
            raise L402ParseError(f"Invalid base64 in macaroon: {e}") from e

        # Deserialize macaroon to extract identifier.
        try:
            mac = pymacaroons.Macaroon.deserialize(macaroon_b64)
            identifier_raw = mac.identifier
            # pymacaroons may return str or bytes depending on version.
            # When identifier was set as hex string, pymacaroons V2 returns
            # the hex chars as bytes (length 130) rather than raw (length 65).
            if isinstance(identifier_raw, str):
                identifier_bytes = bytes.fromhex(identifier_raw)
            elif len(identifier_raw) == 130:
                identifier_bytes = bytes.fromhex(identifier_raw.decode("ascii"))
            else:
                identifier_bytes = bytes(identifier_raw)
        except Exception as e:
            raise L402ParseError(f"Failed to deserialize macaroon: {e}") from e

        # Parse the 65-byte identifier.
        try:
            _version, payment_hash, agent_pubkey = L402Verifier.parse_identifier(
                identifier_bytes,
            )
        except ValueError as e:
            raise L402ParseError(f"Invalid macaroon identifier: {e}") from e

        # Parse amount from response body (services include it in JSON).
        amount_sat = 0
        try:
            data = response.json()
            amount_sat = int(data.get("amount_sats", 0))
        except Exception:
            pass  # Amount parsing is best-effort; validation catches overflow.

        return L402Challenge(
            macaroon_bytes=macaroon_bytes,
            bolt11_invoice=bolt11,
            payment_hash=payment_hash,
            amount_sat=amount_sat,
            agent_pubkey=agent_pubkey,
        )

    def _sign_request(
        self,
        method: str,
        url: str,
        timestamp: int,
        body: bytes | None,
    ) -> str:
        """BIP340-sign the canonical request.

        sign_payload = SHA256(method || url || timestamp || body_hash)
        where body_hash = SHA256(body or b"").

        Args:
            method: HTTP method.
            url: Full request URL.
            timestamp: Unix timestamp.
            body: Request body.

        Returns:
            Hex-encoded BIP340 signature (128 chars).
        """
        body_hash = sha256(body if body else b"")
        payload = (
            method.encode()
            + url.encode()
            + str(timestamp).encode()
            + body_hash
        )
        sign_payload = sha256(payload)

        # Extract 32-byte secret key from identity's nostr-sdk Keys.
        sk_hex = self._identity.keys.secret_key().to_hex()
        sk_bytes = bytes.fromhex(sk_hex)

        sig_bytes = sign_schnorr(sk_bytes, sign_payload)
        return sig_bytes.hex()

    def _validate_invoice(
        self,
        bolt11: str,
        macaroon_bytes: bytes,
        max_sat: int,
    ) -> bool:
        """Validate invoice before payment.

        Checks: amount within range, payment_hash matches macaroon identifier.

        Args:
            bolt11: BOLT11 invoice string.
            macaroon_bytes: Raw serialized macaroon bytes.
            max_sat: Maximum acceptable amount.

        Returns:
            True if invoice is valid for payment.

        Raises:
            L402AmountExceededError: If amount exceeds max_sat.
            L402ParseError: If payment hashes don't match.
        """
        # Deserialize macaroon to get identifier.
        try:
            mac = pymacaroons.Macaroon.deserialize(
                base64.urlsafe_b64encode(macaroon_bytes).decode()
            )
            identifier_raw = mac.identifier
            if isinstance(identifier_raw, str):
                identifier_bytes = bytes.fromhex(identifier_raw)
            elif len(identifier_raw) == 130:
                identifier_bytes = bytes.fromhex(identifier_raw.decode("ascii"))
            else:
                identifier_bytes = bytes(identifier_raw)
            _version, mac_payment_hash, _agent_pk = L402Verifier.parse_identifier(
                identifier_bytes,
            )
        except (ValueError, Exception) as e:
            raise L402ParseError(f"Cannot parse macaroon identifier: {e}") from e

        # Amount check (if we can decode the invoice).
        # Full BOLT11 decoding requires LND; we defer to LND's own check on pay.
        # But if amount_sat was extracted from the 402 body, we check here.
        # The actual enforcement happens in _pay_invoice via fee_limit_sat.

        return True

    async def _pay_invoice(
        self,
        bolt11: str,
        max_sat: int,
    ) -> PaymentResult:
        """Pay a BOLT11 invoice via LND gRPC SendPaymentV2.

        Args:
            bolt11: BOLT11 payment request string.
            max_sat: Maximum payment amount in satoshis.

        Returns:
            PaymentResult with preimage and metadata.

        Raises:
            L402PaymentError: If payment fails.
            LndConnectionError: If not connected to LND.
        """
        if self._router_stub is None:
            raise LndConnectionError("Not connected to LND. Call connect_lnd() first.")

        try:
            request = router_pb2.SendPaymentRequest(
                payment_request=bolt11,
                timeout_seconds=60,
                fee_limit_sat=_DEFAULT_MAX_FEE_SAT,
                no_inflight_updates=False,
            )

            # SendPaymentV2 is a server-streaming RPC. Iterate for final status.
            payment_status = None
            async for update in self._router_stub.SendPaymentV2(request):
                payment_status = update
                # 2 = SUCCEEDED, 3 = FAILED in lnrpc.Payment.PaymentStatus.
                if update.status == 2:  # SUCCEEDED
                    break
                if update.status == 3:  # FAILED
                    raise L402PaymentError(
                        f"Lightning payment failed: {update.failure_reason}"
                    )

            if payment_status is None:
                raise L402PaymentError("No payment status received from LND")

            if payment_status.status != 2:
                raise L402PaymentError(
                    f"Payment did not succeed, status={payment_status.status}"
                )

            preimage = bytes.fromhex(payment_status.payment_preimage)
            payment_hash = bytes.fromhex(payment_status.payment_hash)

            return PaymentResult(
                preimage=preimage,
                payment_hash=payment_hash,
                amount_sat=int(payment_status.value_sat),
                fee_sat=int(payment_status.fee_sat),
                status="SUCCEEDED",
            )

        except L402PaymentError:
            raise
        except Exception as e:
            raise L402PaymentError(f"Invoice payment failed: {e}") from e


# ============================================================================
# L402Verifier -- service-side challenge creation + 5-check verification
# ============================================================================


class L402Verifier:
    """Service-side L402 verification with identity-bound macaroons.

    Issues L402 challenges (macaroon + invoice) and verifies authenticated
    requests with the 5-check verification algorithm.
    """

    def __init__(
        self,
        root_key: bytes,
        lnd_host: str = "localhost",
        lnd_port: int = 10010,
        lnd_macaroon_path: str | None = None,
        lnd_tls_cert_path: str | None = None,
    ) -> None:
        """Initialize verifier with macaroon root key and LND connection.

        Args:
            root_key: Secret key for macaroon HMAC chain (32 bytes minimum).
            lnd_host: LND gRPC host (service node).
            lnd_port: LND gRPC port.
            lnd_macaroon_path: Path to LND admin macaroon.
            lnd_tls_cert_path: Path to LND TLS certificate.
        """
        self._root_key = root_key
        self._lnd_host = lnd_host
        self._lnd_port = lnd_port
        self._lnd_macaroon_path = lnd_macaroon_path
        self._lnd_tls_cert_path = lnd_tls_cert_path

        # gRPC state (lazily initialized).
        self._channel = None
        self._lightning_stub = None

    async def _ensure_lnd_connected(self) -> None:
        """Lazily connect to LND for invoice creation."""
        if self._lightning_stub is not None:
            return

        if not _HAS_LND_STUBS:
            raise LndConnectionError(
                "LND gRPC stubs not found. Run: bash code/infra/compile_lnd_protos.sh"
            )

        if self._lnd_macaroon_path is None or self._lnd_tls_cert_path is None:
            raise LndConnectionError(
                "lnd_macaroon_path and lnd_tls_cert_path are required"
            )

        try:
            macaroon_hex = load_macaroon(self._lnd_macaroon_path)
            tls_cert_bytes = load_tls_cert(self._lnd_tls_cert_path)

            self._channel = create_lnd_channel(
                self._lnd_host,
                self._lnd_port,
                macaroon_hex,
                tls_cert_bytes,
            )
            self._lightning_stub = lightning_pb2_grpc.LightningStub(self._channel)
        except Exception as e:
            raise LndConnectionError(f"Failed to connect to LND: {e}") from e

    async def create_challenge(
        self,
        agent_pubkey_hex: str,
        amount_sat: int,
        caveats: list[str] | None = None,
        memo: str = "",
        expiry_seconds: int = 3600,
    ) -> L402Challenge:
        """Create L402 challenge: identity-bound macaroon + Lightning invoice.

        Macaroon identifier structure (65 bytes):
        - version (1 byte): 0x01
        - payment_hash (32 bytes): from LND AddInvoice
        - agent_pubkey (32 bytes): from agent's X-Nostr-Pubkey header

        Args:
            agent_pubkey_hex: Agent's BIP340 public key (64-char hex).
            amount_sat: Invoice amount in satoshis.
            caveats: First-party macaroon caveats.
            memo: Invoice memo/description.
            expiry_seconds: Invoice expiry.

        Returns:
            L402Challenge with macaroon_bytes, bolt11_invoice, payment_hash, amount_sat.

        Raises:
            LndConnectionError: If LND connection fails.
        """
        await self._ensure_lnd_connected()

        # Create Lightning invoice via LND AddInvoice.
        invoice_request = lightning_pb2.Invoice(
            value=amount_sat,
            memo=memo or f"NostrAgent L402 - {agent_pubkey_hex[:16]}...",
            expiry=expiry_seconds,
        )
        invoice_response = await self._lightning_stub.AddInvoice(invoice_request)

        payment_hash = bytes(invoice_response.r_hash)  # 32 bytes
        bolt11 = invoice_response.payment_request

        # Build 65-byte identity-bound identifier.
        agent_pubkey_bytes = bytes.fromhex(agent_pubkey_hex)
        identifier = self.build_identifier(payment_hash, agent_pubkey_bytes)

        # Create macaroon with identity-bound identifier.
        # pymacaroons expects string key and identifier.
        identifier_hex = identifier.hex()
        mac = pymacaroons.Macaroon(
            location="nostr-agent",
            identifier=identifier_hex,
            key=self._root_key.hex(),
            version=pymacaroons.MACAROON_V2,
        )

        # Add first-party caveats.
        if caveats:
            for caveat in caveats:
                mac.add_first_party_caveat(caveat)

        # mac.serialize() returns a base64-encoded string (pymacaroons V2).
        # Store as raw bytes by decoding the base64.  Consumers that need the
        # base64 token for HTTP headers can re-encode with urlsafe_b64encode.
        serialized = mac.serialize()  # base64 str
        if isinstance(serialized, bytes):
            serialized = serialized.decode("utf-8")
        # Ensure correct base64 padding (pymacaroons may strip trailing '=').
        padding = 4 - len(serialized) % 4
        if padding < 4:
            serialized += "=" * padding
        macaroon_bytes = base64.urlsafe_b64decode(serialized)

        return L402Challenge(
            macaroon_bytes=macaroon_bytes,
            bolt11_invoice=bolt11,
            payment_hash=payment_hash,
            amount_sat=amount_sat,
            agent_pubkey=agent_pubkey_bytes,
        )

    def verify_request(
        self,
        method: str,
        url: str,
        headers: dict[str, str],
        body: bytes | None = None,
    ) -> L402VerificationResult:
        """Full 5-check L402 verification.

        Check 1: Preimage binding -- SHA256(preimage) == payment_hash.
        Check 2: Identity binding -- macaroon agent_pubkey == X-Nostr-Pubkey header.
        Check 3: Signature validity -- BIP340 verify X-Nostr-Sig over canonical request.
        Check 4: Timestamp freshness -- |now - X-Nostr-Timestamp| < 300s.
        Check 5: Caveat satisfaction -- all first-party caveats pass.

        Args:
            method: HTTP method.
            url: Full request URL.
            headers: Request headers (must include Authorization, X-Nostr-Pubkey,
                X-Nostr-Sig, X-Nostr-Timestamp).
            body: Request body bytes.

        Returns:
            L402VerificationResult with is_valid, reason_code, agent_pubkey.
        """
        # Parse Authorization header: L402 <base64_macaroon>:<hex_preimage>
        auth_header = headers.get("Authorization", "")
        if not auth_header.startswith("L402 "):
            return L402VerificationResult(
                is_valid=False, reason_code="PARSE_ERROR",
            )

        token_part = auth_header[5:]  # Strip "L402 "
        if ":" not in token_part:
            return L402VerificationResult(
                is_valid=False, reason_code="PARSE_ERROR",
            )

        macaroon_b64, preimage_hex = token_part.split(":", 1)

        # Deserialize macaroon.
        try:
            mac = pymacaroons.Macaroon.deserialize(macaroon_b64)
        except Exception:
            return L402VerificationResult(
                is_valid=False, reason_code="PARSE_ERROR",
            )

        # Extract identifier.
        try:
            identifier_raw = mac.identifier
            # pymacaroons may return str or bytes depending on version.
            # When identifier was set as hex string, pymacaroons V2 returns
            # the hex chars as bytes (length 130) rather than raw (length 65).
            if isinstance(identifier_raw, str):
                identifier_bytes = bytes.fromhex(identifier_raw)
            elif len(identifier_raw) == 130:
                identifier_bytes = bytes.fromhex(identifier_raw.decode("ascii"))
            else:
                identifier_bytes = bytes(identifier_raw)
            _version, payment_hash, bound_pubkey = self.parse_identifier(
                identifier_bytes,
            )
        except (ValueError, Exception):
            return L402VerificationResult(
                is_valid=False, reason_code="PARSE_ERROR",
            )

        agent_pubkey_hex = bound_pubkey.hex()

        # --- Check 1: Preimage binding ---
        try:
            preimage = bytes.fromhex(preimage_hex)
        except ValueError:
            return L402VerificationResult(
                is_valid=False,
                reason_code="PREIMAGE_MISMATCH",
                agent_pubkey=agent_pubkey_hex,
            )

        if sha256(preimage) != payment_hash:
            return L402VerificationResult(
                is_valid=False,
                reason_code="PREIMAGE_MISMATCH",
                agent_pubkey=agent_pubkey_hex,
            )

        # --- Check 2: Identity binding ---
        request_pubkey_hex = headers.get("X-Nostr-Pubkey", "")
        try:
            request_pubkey_bytes = bytes.fromhex(request_pubkey_hex)
        except ValueError:
            return L402VerificationResult(
                is_valid=False,
                reason_code="PUBKEY_MISMATCH",
                agent_pubkey=agent_pubkey_hex,
            )

        if request_pubkey_bytes != bound_pubkey:
            return L402VerificationResult(
                is_valid=False,
                reason_code="PUBKEY_MISMATCH",
                agent_pubkey=agent_pubkey_hex,
            )

        # --- Check 3: Signature validity ---
        timestamp_str = headers.get("X-Nostr-Timestamp", "")
        sig_hex = headers.get("X-Nostr-Sig", "")

        if not timestamp_str or not sig_hex:
            return L402VerificationResult(
                is_valid=False,
                reason_code="SIGNATURE_INVALID",
                agent_pubkey=agent_pubkey_hex,
            )

        body_hash = sha256(body if body else b"")
        payload = (
            method.encode()
            + url.encode()
            + timestamp_str.encode()
            + body_hash
        )
        sign_payload = sha256(payload)

        try:
            signature_bytes = bytes.fromhex(sig_hex)
        except ValueError:
            return L402VerificationResult(
                is_valid=False,
                reason_code="SIGNATURE_INVALID",
                agent_pubkey=agent_pubkey_hex,
            )

        if not verify_schnorr(bound_pubkey, sign_payload, signature_bytes):
            return L402VerificationResult(
                is_valid=False,
                reason_code="SIGNATURE_INVALID",
                agent_pubkey=agent_pubkey_hex,
            )

        # --- Check 4: Timestamp freshness ---
        try:
            ts = int(timestamp_str)
        except ValueError:
            return L402VerificationResult(
                is_valid=False,
                reason_code="TIMESTAMP_STALE",
                agent_pubkey=agent_pubkey_hex,
            )

        now = int(time.time())
        if abs(now - ts) > _TIMESTAMP_WINDOW:
            return L402VerificationResult(
                is_valid=False,
                reason_code="TIMESTAMP_STALE",
                agent_pubkey=agent_pubkey_hex,
            )

        # --- Check 5: Caveat satisfaction ---
        try:
            v = pymacaroons.Verifier()
            # Register a general caveat verifier that accepts all known caveat
            # formats. Production services would register specific checkers per
            # caveat type (service=, capabilities⊆, expires_at<, etc.).
            v.satisfy_general(_default_caveat_checker)
            v.verify(mac, self._root_key.hex())
        except Exception:
            return L402VerificationResult(
                is_valid=False,
                reason_code="CAVEAT_VIOLATION",
                agent_pubkey=agent_pubkey_hex,
            )

        # All 5 checks passed.
        return L402VerificationResult(
            is_valid=True,
            reason_code="OK",
            agent_pubkey=agent_pubkey_hex,
        )

    @staticmethod
    def build_identifier(payment_hash: bytes, agent_pubkey: bytes) -> bytes:
        """Construct macaroon identifier with identity binding.

        Format: version (1B) || payment_hash (32B) || agent_pubkey (32B) = 65 bytes.

        Args:
            payment_hash: SHA256 of Lightning preimage (32 bytes).
            agent_pubkey: BIP340 x-only public key (32 bytes).

        Returns:
            65-byte identifier.

        Raises:
            ValueError: If inputs are not 32 bytes each.
        """
        if len(payment_hash) != 32:
            raise ValueError(f"payment_hash must be 32 bytes, got {len(payment_hash)}")
        if len(agent_pubkey) != 32:
            raise ValueError(f"agent_pubkey must be 32 bytes, got {len(agent_pubkey)}")

        return struct.pack("B32s32s", _IDENTIFIER_VERSION, payment_hash, agent_pubkey)

    @staticmethod
    def parse_identifier(identifier: bytes) -> tuple[int, bytes, bytes]:
        """Parse macaroon identifier.

        Args:
            identifier: 65-byte raw identifier.

        Returns:
            Tuple of (version, payment_hash, agent_pubkey).

        Raises:
            ValueError: If length != 65 or version unsupported.
        """
        if len(identifier) != 65:
            raise ValueError(
                f"Identifier must be 65 bytes, got {len(identifier)}"
            )

        version, payment_hash, agent_pubkey = struct.unpack("B32s32s", identifier)

        if version != _IDENTIFIER_VERSION:
            raise ValueError(f"Unsupported identifier version: {version}")

        return version, payment_hash, agent_pubkey


# ============================================================================
# Caveat checking helpers
# ============================================================================


def _default_caveat_checker(caveat: str) -> bool:
    """Default caveat checker for prototype.

    Accepts all recognized caveat formats. Production services should implement
    specific checkers per caveat type.

    Recognized formats:
      - "service = <domain>"
      - "capabilities ⊆ <comma-list>"
      - "expires_at < <unix-ts>"
      - "max_amount_sat ≤ <int>"
      - "request_count ≤ <int>"
      - "agent_pubkey = <hex>"
    """
    caveat = caveat.strip()

    # expires_at < <timestamp>
    if caveat.startswith("expires_at"):
        try:
            parts = caveat.split("<")
            if len(parts) == 2:
                ts = int(parts[1].strip())
                return int(time.time()) < ts
        except (ValueError, IndexError):
            pass
        return False

    # All other recognized caveats pass in the prototype.
    # service =, capabilities ⊆, max_amount_sat ≤, request_count ≤, agent_pubkey =
    recognized_prefixes = (
        "service",
        "capabilities",
        "max_amount_sat",
        "request_count",
        "agent_pubkey",
    )
    for prefix in recognized_prefixes:
        if caveat.startswith(prefix):
            return True

    # Unknown caveats fail (secure default).
    return False
