"""LND gRPC package -- compiled protobuf stubs and credential helpers.

Stubs (lightning_pb2, lightning_pb2_grpc, router_pb2, router_pb2_grpc) are
generated by code/infra/compile_lnd_protos.sh.  Run that script once before
importing stubs.

Credential helpers (load_macaroon, create_lnd_channel, get_lnd_stub, etc.)
are re-exported from .credentials for backward compatibility.
"""

from nostr_agent.lnd_grpc.credentials import (
    LNDCredentialError,
    create_lnd_channel,
    extract_lnd_credentials_from_docker,
    get_lnd_stub,
    load_macaroon,
    load_tls_cert,
)

__all__ = [
    "LNDCredentialError",
    "create_lnd_channel",
    "extract_lnd_credentials_from_docker",
    "get_lnd_stub",
    "load_macaroon",
    "load_tls_cert",
]
